version: '3.8'

services:
  web:
    build: .
    container_name: cifs-dev
    ports:
      - "2020:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      BASE_PATH: ${BASE_PATH:-}
    volumes:
      - .:/var/www/html
    restart: unless-stopped
